In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [9]:
#load the dataset
data = pd.read_csv('C:\\Users\\tanis\\Desktop\\Deep_learning_pjt\\Churn_Modelling.csv')
data.head(5)

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [10]:
#preprocessing the data
#drop the unnecessary columns
data=data.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [11]:
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [12]:
#Encode the categorical variables
label_encoder_gender = LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])
data

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France       0  ...               1        101348.88       1
1             608     Spain       0  ...               1        112542.58       0
2             502    France       0  ...               0        113931.57       1
3             699    France       0  ...               0         93826.63       0
4             850     Spain       0  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France       1  ...               0         96270.64       0
9996          516    France       1  ...               1        101699.77       0
9997          709    France       0  ...               1         42085.58       1
9998          772   Germany       1  ...               0         92888.52       1
9999          792    France       0  ...               0         38190.78       0

[10000 rows x 11 columns]

In [13]:
#Onehot encoding for the 'Geography' column
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[['Geography']])
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [14]:
onehot_encoder_geo.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [15]:
geo_encoded_df=pd.DataFrame(geo_encoder.toarray(),columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [16]:
data=pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [17]:
#save the encoders and  scalers
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

In [22]:
#Divide the dataset into dependent and independent variables
X=data.drop('Exited',axis=1)
y=data['Exited']   

#split the dataset into training and testing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

#Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)    
X_test=scaler.transform(X_test)

In [23]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [24]:
with open("scaler.pkl","wb") as file:
    pickle.dump(scaler,file)

In [25]:
data

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 13 columns]

ANN Implementation

In [26]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense   
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [27]:
(X_train.shape[1],)

(12,)

In [29]:
#Build the ANN model
model=Sequential([
    Dense(64,activation="relu",input_shape=(X_train.shape[1],)),# HL1 Connected with input layer
    Dense(32,activation="relu"),# HL2   
    Dense(1,activation="sigmoid")# output layer

])

In [30]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_1 (Dense)             (None, 64)                832

 dense_2 (Dense)             (None, 32)                2080

 dense_3 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [32]:
import tensorflow 
opt=tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss=tensorflow.keras.losses.BinaryCrossentropy()
loss

In [33]:
#compile the model
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [36]:
#Setup the TensorBoard
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir, histogram_freq=1)

In [37]:
#setup early stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=5,restore_best_weights=True)

In [38]:
#training the model
history=model.fit(X_train,y_train,validation_data=(X_test,y_test),epochs=100,batch_size=32,callbacks=[tensorboard_callback,early_stopping_callback])

Epoch 1/100
WARNING:tensorflow:From c:\Users\tanis\Desktop\Deep_learning_pjt\venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\tanis\Desktop\Deep_learning_pjt\venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 4s 7ms/step - loss: 0.3971 - accuracy: 0.8378 - val_loss: 0.3594 - val_accuracy: 0.8530
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3560 - accuracy: 0.8525 - val_loss: 0.3483 - val_accuracy: 0.8675
Epoch 3/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3505 - accuracy: 0.8558 - val_loss: 0.3557 - val_accuracy: 0.8480
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3437 - accuracy: 0.8599 - val_loss: 0.3499 - val_accuracy: 0.8595
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3411 - accuracy: 0.8633 - val_loss: 0.3495 - val_accuracy: 0.8565
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3395 - accuracy: 0.8625 - val_loss: 0.3450 - val_accuracy: 0.8600
Epoch 7/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3364 - accuracy: 0.8626 - val_loss: 0.3499 - val_accuracy: 0.8620
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3354 - accuracy: 0.8631 - val_loss: 0.3462 - val_accuracy: 0.8605
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3338 - accuracy: 0.8625 - val_loss: 0.3411 - val_accuracy: 0.8605
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3289 - accuracy: 0.8639 - val_loss: 0.3407 - val_accuracy: 0.8605
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3291 - accuracy: 0.8658 - val_loss: 0.3423 - val_accuracy: 0.8595
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3245 - accuracy: 0.8666 - val_loss: 0.3648 - val_accuracy: 0.8595
Epoch 13/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3252 - accuracy: 0.8635 - val_loss: 0.3482 - val_accuracy: 0.8600
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3236 - accuracy: 0.8668 - val_loss: 0.3631 - val_accuracy: 0.8620
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3206 - accuracy: 0.8680 - val_loss: 0.3529 - val_accuracy: 0.8580

In [39]:
model.save('model.h5')

c:\Users\tanis\Desktop\Deep_learning_pjt\venv\Lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [7]:
#Load TensorBoard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [8]:
%tensorboard --logdir logs/fit

ERROR: Failed to launch TensorBoard (exited with 1).
Contents of stderr:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\tanis\Desktop\Deep_learning_pjt\venv\Scripts\tensorboard.exe\__main__.py", line 2, in <module>
  File "c:\Users\tanis\Desktop\Deep_learning_pjt\venv\Lib\site-packages\tensorboard\main.py", line 27, in <module>
    from tensorboard import default
  File "c:\Users\tanis\Desktop\Deep_learning_pjt\venv\Lib\site-packages\tensorboard\default.py", line 30, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

In [9]:
import pkg_resources
print("working")

ModuleNotFoundError: No module named 'pkg_resources'

In [10]:
import sys
!{sys.executable} -m pip install --upgrade --force-reinstall setuptools

Collecting setuptools
  Downloading setuptools-82.0.1-py3-none-any.whl.metadata (6.5 kB)
Downloading setuptools-82.0.1-py3-none-any.whl (1.0 MB)
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.0 MB ? eta -:--:--
   ---------- ----------------------------- 0.3/1.0 MB ? eta -:--:--
   ------------------------------- -------- 0.8/1.0 MB 2.4 MB/s eta 0:00:01
   ---------------------------------------- 1.0/1.0 MB 2.4 MB/s  0:00:00
Installing collected packages: setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 82.0.1
    Uninstalling setuptools-82.0.1:
      Successfully uninstalled setuptools-82.0.1
Successfully installed setuptools-82.0.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow-intel 2.15.0 requires tensorboard<2.16,>=2.15, but you have tensorboard 2.20.0 which is incompatible.

In [ ]:
import pkg_resources
print("working")

ModuleNotFoundError: No module named 'pkg_resources'